# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/blog
  docker:
    - image: circleci/openjdk:8-jdk-node-browsers

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}.
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: yarn test --maxWorkers=2

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/blog
          paths: .

  deploy:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}.
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: yarn test --maxWorkers=2

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn deploy

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
